# one dimensional array

In [3]:
import numpy as np

 One-dimensional Arrays
 Q-1) MegaCity Builders is a construction company. They seek the help of their data analyst to generate employee codes from 1 to 1,000 for their part time work force, as they are not interested in RDBMS solution.

In [3]:
emp_code = np.arange(1,1001)
emp_code

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [4]:
#generate numbers from 201 to 700

number = np.arange(201,701)
number

 Q-2)  MegaCity Builders has a total of 1,000 part-time employees. The annual salaries of these employees lie between $10,000 and $20,000. The company wishes to find the average annual salary of the employees.

In [5]:
salary = np.random.randint(10000,20000,1000)
salary

array([15000, 15055, 10983, 11245, 15112, 19467, 16066, 19053, 17374,
       18948, 13615, 19268, 13118, 14202, 19796, 18063, 14886, 15920,
       17244, 12966, 18595, 16855, 16621, 19943, 10581, 11026, 14542,
       17022, 17242, 13072, 13164, 11904, 17048, 17584, 14333, 19380,
       16171, 13260, 14671, 12765, 16717, 11091, 15995, 16251, 13735,
       12840, 17338, 11434, 13055, 14026, 14582, 15950, 12726, 14331,
       16189, 11195, 12518, 10569, 12811, 17370, 15794, 18404, 16706,
       10706, 18845, 17280, 18591, 12536, 14981, 12225, 10106, 11775,
       17404, 16495, 15489, 10333, 17137, 16223, 12657, 16882, 12463,
       10156, 18559, 15764, 12768, 11875, 16112, 10457, 16825, 17260,
       14793, 15830, 10172, 15186, 19348, 13266, 12930, 19499, 12551,
       16133, 17149, 13552, 16501, 10707, 11029, 16094, 14077, 12914,
       18853, 16912, 19495, 10107, 16496, 16443, 18788, 12980, 15895,
       19804, 19748, 17705, 11452, 15534, 19852, 11332, 12064, 10336,
       13899, 15147,

In [6]:
avg_salary = np.mean(salary)             #here , used np.mean to find the average of the salary
avg_salary


14988.798

In [7]:
#generate 500 such numbers here salary is 20000 to 30000

sal = np.random.randint(20000,30000,500)
sal

 Q-3) The HR wishes to know how many employees are getting salaries more than $15,000 per year.

In [8]:
salary.size

1000

In [9]:
indx = salary>15000 

In [10]:
index = np.where(indx)               #index, so it will tell use the index point where the salaries are greater than 15k 
index

(array([  1,   4,   5,   6,   7,   8,   9,  11,  14,  15,  17,  18,  20,
         21,  22,  23,  27,  28,  32,  33,  35,  36,  40,  42,  43,  46,
         51,  54,  59,  60,  61,  62,  64,  65,  66,  72,  73,  74,  76,
         77,  79,  82,  83,  86,  88,  89,  91,  93,  94,  97,  99, 100,
        102, 105, 108, 109, 110, 112, 113, 114, 116, 117, 118, 119, 121,
        122, 127, 128, 130, 131, 132, 134, 135, 136, 137, 138, 139, 142,
        143, 146, 149, 155, 156, 157, 160, 162, 164, 165, 168, 173, 175,
        176, 178, 182, 189, 191, 193, 194, 195, 196, 197, 199, 202, 204,
        205, 206, 207, 209, 210, 211, 212, 214, 216, 218, 219, 222, 226,
        227, 228, 229, 233, 234, 235, 236, 238, 241, 242, 248, 249, 250,
        252, 255, 258, 261, 262, 263, 264, 268, 269, 270, 271, 272, 275,
        276, 280, 282, 283, 284, 286, 288, 289, 290, 291, 292, 293, 295,
        297, 298, 299, 301, 303, 304, 305, 306, 307, 308, 309, 310, 312,
        313, 315, 320, 322, 324, 326, 327, 328, 329

In [11]:
salary[10]         #example if we want to see the salary 

13615

In [12]:
salary [1:100]

array([15055, 10983, 11245, 15112, 19467, 16066, 19053, 17374, 18948,
       13615, 19268, 13118, 14202, 19796, 18063, 14886, 15920, 17244,
       12966, 18595, 16855, 16621, 19943, 10581, 11026, 14542, 17022,
       17242, 13072, 13164, 11904, 17048, 17584, 14333, 19380, 16171,
       13260, 14671, 12765, 16717, 11091, 15995, 16251, 13735, 12840,
       17338, 11434, 13055, 14026, 14582, 15950, 12726, 14331, 16189,
       11195, 12518, 10569, 12811, 17370, 15794, 18404, 16706, 10706,
       18845, 17280, 18591, 12536, 14981, 12225, 10106, 11775, 17404,
       16495, 15489, 10333, 17137, 16223, 12657, 16882, 12463, 10156,
       18559, 15764, 12768, 11875, 16112, 10457, 16825, 17260, 14793,
       15830, 10172, 15186, 19348, 13266, 12930, 19499, 12551, 16133])

In [13]:
salary[index]          #these are the salaries which are greater than 15k

array([15055, 15112, 19467, 16066, 19053, 17374, 18948, 19268, 19796,
       18063, 15920, 17244, 18595, 16855, 16621, 19943, 17022, 17242,
       17048, 17584, 19380, 16171, 16717, 15995, 16251, 17338, 15950,
       16189, 17370, 15794, 18404, 16706, 18845, 17280, 18591, 17404,
       16495, 15489, 17137, 16223, 16882, 18559, 15764, 16112, 16825,
       17260, 15830, 15186, 19348, 19499, 16133, 17149, 16501, 16094,
       18853, 16912, 19495, 16496, 16443, 18788, 15895, 19804, 19748,
       17705, 15534, 19852, 15147, 17603, 15921, 18013, 17555, 15353,
       15681, 16219, 19617, 19495, 16160, 16746, 17538, 16750, 17436,
       17695, 16595, 16126, 17170, 18694, 17336, 17129, 15829, 15847,
       19624, 17648, 15915, 18778, 17702, 16556, 16381, 19172, 16253,
       17582, 18606, 19881, 18400, 16835, 19483, 19640, 19122, 17135,
       17562, 16431, 19040, 17118, 15154, 18970, 17107, 19024, 15631,
       17712, 17936, 19397, 19789, 15360, 16303, 16000, 17831, 17314,
       15146, 16935,

In [14]:
salary[index].size

513

In [15]:
#find out how many people having salary greater than 17000

In [16]:
inx = salary>17000

In [17]:
index = np.where(inx)
index

(array([  5,   7,   8,   9,  11,  14,  15,  18,  20,  23,  27,  28,  32,
         33,  35,  46,  59,  61,  64,  65,  66,  72,  76,  82,  89,  94,
         97, 100, 108, 110, 114, 117, 118, 119, 122, 128, 131, 132, 137,
        138, 143, 149, 155, 160, 162, 164, 165, 175, 176, 182, 189, 194,
        196, 197, 199, 202, 205, 206, 207, 209, 210, 212, 214, 218, 219,
        222, 227, 228, 229, 233, 238, 241, 249, 250, 252, 255, 258, 261,
        263, 268, 269, 271, 272, 275, 283, 288, 289, 290, 292, 293, 297,
        301, 304, 305, 306, 308, 309, 312, 315, 322, 324, 326, 328, 329,
        333, 341, 342, 345, 349, 358, 360, 366, 369, 370, 373, 377, 378,
        379, 381, 382, 390, 399, 400, 409, 414, 416, 418, 427, 430, 431,
        435, 444, 447, 451, 452, 453, 454, 457, 459, 460, 461, 462, 465,
        469, 470, 480, 481, 483, 486, 488, 493, 496, 499, 502, 503, 506,
        511, 513, 517, 518, 521, 524, 525, 528, 530, 538, 541, 543, 545,
        552, 553, 558, 567, 578, 581, 585, 589, 590

In [18]:
salary[index]

array([19467, 19053, 17374, 18948, 19268, 19796, 18063, 17244, 18595,
       19943, 17022, 17242, 17048, 17584, 19380, 17338, 17370, 18404,
       18845, 17280, 18591, 17404, 17137, 18559, 17260, 19348, 19499,
       17149, 18853, 19495, 18788, 19804, 19748, 17705, 19852, 17603,
       18013, 17555, 19617, 19495, 17538, 17436, 17695, 17170, 18694,
       17336, 17129, 19624, 17648, 18778, 17702, 19172, 17582, 18606,
       19881, 18400, 19483, 19640, 19122, 17135, 17562, 19040, 17118,
       18970, 17107, 19024, 17712, 17936, 19397, 19789, 17831, 17314,
       17650, 18578, 18852, 18140, 19248, 19760, 19331, 19472, 18963,
       17427, 19390, 18634, 18052, 19677, 17043, 18169, 17049, 17053,
       18444, 19540, 19810, 19058, 19516, 18819, 17072, 18750, 17744,
       18757, 18064, 17690, 17105, 18649, 18098, 17475, 17037, 18629,
       19050, 17322, 19580, 19134, 19852, 17627, 19327, 17042, 19644,
       19975, 19740, 19509, 19168, 17991, 18127, 19050, 18661, 19562,
       18757, 18410,

In [19]:
salary[index].size

293

 Q-4) The employees with the codes 5, 124, 200, 332, 420, 589, 665, 743, 887, and 901 want to resign. As per the policy, the company does not save the data of part-time employees once they resign.  How can you delete the record/data of these employees? Consider the array "dup" to contain a copy of the employee codes.

In [1]:
dup  = emp_code.copy()

NameError: name 'emp_code' is not defined

In [21]:
t1 = ( 5-1, 124-1, 200-1, 332-1, 420-1, 589-1, 665-1, 743-1, 887-1, 901-1)

number       #Example

deleted = np.delete(number,0 ,axis= 0)
deleted

np.delete(deleted, 6 ,axis= 0)

In [22]:
new_dup = np.delete(emp_code, t1, axis = 0)
new_dup

array([   1,    2,    3,    4,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

 Q-5) The HR wants to hire 10 new employees, assign them the employee codes from 1001 to 1010, and add the data in the existing employee codes. How can you accomplish this task? Consider the array "empid" which originally contains the employee IDs.

In [23]:
new_emp = np.arange(1001,1011)
new_emp

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [24]:
emp_code = np.append(new_dup,new_emp)
emp_code

array([   1,    2,    3,    4,    6,    7,    8,    9,   10,   11,   12,
         13,   14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
         24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
         35,   36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
         46,   47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
         57,   58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
         68,   69,   70,   71,   72,   73,   74,   75,   76,   77,   78,
         79,   80,   81,   82,   83,   84,   85,   86,   87,   88,   89,
         90,   91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
        101,  102,  103,  104,  105,  106,  107,  108,  109,  110,  111,
        112,  113,  114,  115,  116,  117,  118,  119,  120,  121,  122,
        123,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

 Q-6) The company wants to know and display the top 10 highest salaries of employees. The array 'salary' contains the salaries of all employees.

In [29]:
salary_desc = np.sort(salary)[::-1]
salary_desc

array([19975, 19972, 19958, 19943, 19928, 19896, 19881, 19863, 19852,
       19852, 19810, 19808, 19804, 19796, 19789, 19788, 19781, 19770,
       19760, 19748, 19746, 19740, 19734, 19730, 19718, 19677, 19675,
       19674, 19654, 19644, 19640, 19624, 19618, 19617, 19584, 19580,
       19562, 19555, 19552, 19546, 19540, 19537, 19516, 19509, 19503,
       19503, 19499, 19495, 19495, 19487, 19483, 19475, 19472, 19467,
       19433, 19418, 19397, 19390, 19381, 19380, 19364, 19357, 19355,
       19352, 19348, 19331, 19327, 19321, 19314, 19268, 19268, 19248,
       19246, 19227, 19217, 19209, 19206, 19195, 19177, 19173, 19172,
       19168, 19159, 19143, 19140, 19134, 19134, 19125, 19122, 19096,
       19058, 19053, 19050, 19050, 19041, 19040, 19033, 19024, 18996,
       18991, 18970, 18964, 18963, 18954, 18948, 18885, 18853, 18852,
       18845, 18835, 18833, 18827, 18823, 18819, 18812, 18812, 18788,
       18778, 18765, 18757, 18757, 18750, 18749, 18728, 18711, 18705,
       18695, 18694,

In [28]:
salary_desc[:10]

array([19975, 19972, 19958, 19943, 19928, 19896, 19881, 19863, 19852,
       19852])

In [98]:
print("Top ten highest salaries of employess are: ",salary_desc[:10])

Top ten highest salaries of employess are:  [19999 19998 19986 19983 19969 19933 19904 19899 19898 19897]


In [53]:
from numpy import genfromtxt

In [55]:
data = genfromtxt('DS1_C4_S1_EmployeeCode_Concept.csv',delimiter=',',skip_header=1)
data

array([1010., 1011., 1012., 1013., 1014., 1015., 1016., 1017., 1018.,
       1019., 1020., 1021., 1022., 1023., 1024., 1025., 1026., 1027.,
       1028., 1029.])

# Two dimensional array

 Q-1) A company wishes to allocate the employee codes from 101 to 105 along with the ages 25, 26, 27, 28, and 29 (in years) to its employees. How can you represent this data using arrays?

In [56]:
ep_code=[101,102,103,104,105]
ep_age = [25,26,27,28,29]

In [57]:
emp_data = np.array([ep_code,ep_age])
emp_data

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [58]:
emp_data.shape                 

(2, 5)

In [59]:
emp_data.size

10

In [60]:
emp_data.ndim                 #number of dimension

2

In [63]:
emp_data.T                  #to transpose the data

array([[101,  25],
       [102,  26],
       [103,  27],
       [104,  28],
       [105,  29]])

In [64]:
np.random.randint(10,20,size=(3,4))                   #create a 3x4 array       

array([[13, 12, 12, 17],
       [18, 14, 19, 15],
       [17, 12, 10, 16]])

In [66]:
emp_data[0]         #first row

array([101, 102, 103, 104, 105])

In [67]:
emp_data[1]                #second row

array([25, 26, 27, 28, 29])

In [ ]:
#print age of 4th 

In [68]:
emp_data[1][3]

28

In [69]:
emp_data[1][1]

26

In [74]:
emp_data[0:,2:]

array([[103, 104, 105],
       [ 27,  28,  29]])

In [80]:
ind =emp_data[0]==105
ind

array([False, False, False, False,  True])

In [81]:
index=np.where(ind)
index

(array([4], dtype=int64),)

In [84]:
emp_data[1][index]

array([29])

In [85]:
emp_data

array([[101, 102, 103, 104, 105],
       [ 25,  26,  27,  28,  29]])

In [93]:
index=np.where(emp_data[0]==103)


In [95]:
emp_data[1][index]=31

In [96]:
emp_data

array([[101, 102, 103, 104, 105],
       [ 25,  26,  31,  28,  29]])

In [30]:
emp_data =np.random.randint(10,20,size=(2,10))
emp_data

array([[13, 17, 19, 14, 12, 18, 17, 15, 10, 17],
       [16, 17, 12, 17, 18, 18, 19, 16, 16, 17]])

In [31]:
emp_data[0]==15

array([False, False, False, False, False, False, False,  True, False,
       False])

In [32]:
index = np.where(emp_data[0]==15)
index

(array([7], dtype=int64),)

In [36]:
emp_data[:,index]

array([[[15]],

       [[16]]])

In [37]:
emp_data[1,index] =0
emp_data

array([[13, 17, 19, 14, 12, 18, 17, 15, 10, 17],
       [16, 17, 12, 17, 18, 18, 19,  0, 16, 17]])

In [5]:
rollno = [1,2,3,4,5,6,7,8,9,10]
marks = [56,76,87,98,63,69,61,90,26,45]

In [6]:
student = np.array([rollno,marks])

In [7]:
student

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [56, 76, 87, 98, 63, 69, 61, 90, 26, 45]])

In [8]:
np.sum(student[1])

671

In [9]:
np.mean(student[1])              #average

67.1

In [10]:
np.min(student[1])

26

In [11]:
np.max(student[1])

98

In [12]:
np.median(student[1])

66.0

In [13]:
age =[12,13,12,14,13,15,16,13,13,14]
student =np.append(student,[age], axis=0)

In [14]:

student

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [56, 76, 87, 98, 63, 69, 61, 90, 26, 45],
       [12, 13, 12, 14, 13, 15, 16, 13, 13, 14]])

In [15]:
student = np.append(student, [[11],[80],[15]], axis=1)
student

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [56, 76, 87, 98, 63, 69, 61, 90, 26, 45, 80],
       [12, 13, 12, 14, 13, 15, 16, 13, 13, 14, 15]])

In [16]:
student = np.append(student, [[15],[90],[15]], axis=1)
student

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 15],
       [56, 76, 87, 98, 63, 69, 61, 90, 26, 45, 80, 90],
       [12, 13, 12, 14, 13, 15, 16, 13, 13, 14, 15, 15]])

In [17]:
student1 = np.delete(student,3,axis=1)                    #deleting column wise therefore using axis=1
student1

array([[ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 15],
       [56, 76, 87, 63, 69, 61, 90, 26, 45, 80, 90],
       [12, 13, 12, 13, 15, 16, 13, 13, 14, 15, 15]])

In [18]:
student

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 15],
       [56, 76, 87, 98, 63, 69, 61, 90, 26, 45, 80, 90],
       [12, 13, 12, 14, 13, 15, 16, 13, 13, 14, 15, 15]])

In [26]:
index = np.where(student[1]<50)
index

(array([8, 9], dtype=int64),)

In [20]:
student[:,index]

array([[[ 9, 10]],

       [[26, 45]],

       [[13, 14]]])