In [1]:
import numpy as np

Task 1
The company has hired 30 candidates recently. Assign the employee IDs to these 30 candidates as per the details below. Save the employee IDs in separate 1D arrays, one for each department, and print them.


 Dept     No.of employees        Range of emp IDS
 HR           3                       1-3
 IT           15                      4-18
 Finance      5                       19-23
 sales        7                       24-30

In [2]:
HR_id=np.arange(1,4)
HR_id


array([1, 2, 3])

In [3]:
IT_id = np.arange(4,19)
IT_id

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
Finance_id =np.arange(19,24)
Finance_id

array([19, 20, 21, 22, 23])

In [5]:
sales_id = np.arange(24,31)
sales_id 

array([24, 25, 26, 27, 28, 29, 30])

Task 2
Create four different 1D arrays to hold only the salaries of the employees as per the details below and print them.

In [6]:
hr_sal = [50000,60000,57000]
Hr_salary = np.array(hr_sal)
Hr_salary

array([50000, 60000, 57000])

In [7]:
IT_sal = [67000,67000,67000,67000,67000,67000,67000,67000,67000,67000,67000,67000,67000,67000,67000]
IT_salary =np.array(IT_sal)
IT_salary

array([67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000, 67000,
       67000, 67000, 67000, 67000, 67000, 67000])

In [8]:
finance_sal = [60000,65000,50000,70000,87000]
finance_salary = np.array(finance_sal)
finance_salary

array([60000, 65000, 50000, 70000, 87000])

In [9]:
sales_sal = [50000, 60000, 65000, 90000, 56000, 65000, 71000]
sales_salary = np.array(sales_sal)
sales_salary

array([50000, 60000, 65000, 90000, 56000, 65000, 71000])

Task 3

Calculate the department-wise average salary expenses on the 30 employees. Also, determine the department with the highest average salary expense on the employees

In [10]:
avg_hr_salary =np.mean(Hr_salary)
print("avergae salary of HR dept: ",avg_hr_salary)
avg_IT_salary =np.mean(IT_salary)
print("avergae salary of IT dept: ",avg_IT_salary)
avg_finance_salary = np.mean(finance_salary)
print("avergae salary of finance dept: ",avg_finance_salary)
avg_sales_salary = np.mean(sales_salary)
print("avergae salary of sales dept: ",avg_sales_salary)

avergae salary of HR dept:  55666.666666666664
avergae salary of IT dept:  67000.0
avergae salary of finance dept:  66400.0
avergae salary of sales dept:  65285.71428571428


In [11]:
 #IT department has the Highest avergae salary 

Task4:

List the highest salaries in HR and finance departments

In [12]:
max_sal_HR = np.max(Hr_salary)
max_sal_finance =np.max(finance_salary)

print("highest salary in HR and finance departments are : ",max_sal_HR ,'and', max_sal_finance )

highest salary in HR and finance departments are :  60000 and 87000


Task 5 

The company has decided to give a joining/signing bonus worth 5% of the gross salary to those employees whose employees who belong to the IT department. Update the salary of such employees after adding the bonus. Display the updated salaries.

In [13]:
update_salary_IT = IT_salary*(0.05)

IT_bonus = update_salary_IT+IT_salary

print("IT salary with Bonus : ",IT_bonus) 

IT salary with Bonus :  [70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350.
 70350. 70350. 70350. 70350. 70350.]


Task 1 

In [14]:
from numpy import genfromtxt

In [15]:
addmis_data = genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice.csv',delimiter=',',skip_header = 1)
addmis_data

array([[  1.  , 337.  , 118.  , ...,   9.65,   1.  ,   0.92],
       [  2.  , 324.  , 107.  , ...,   8.87,   1.  ,   0.76],
       [  3.  , 316.  , 104.  , ...,   8.  ,   1.  ,   0.72],
       ...,
       [398.  , 330.  , 116.  , ...,   9.45,   1.  ,   0.91],
       [399.  , 312.  , 103.  , ...,   8.78,   0.  ,   0.67],
       [400.  , 333.  , 117.  , ...,   9.66,   1.  ,   0.95]])

Task 2 Display the GRE score of all the students.


In [16]:
addmis_data[:,1]

array([337., 324., 316., 322., 314., 330., 321., 308., 302., 323., 325.,
       327., 328., 307., 311., 314., 317., 319., 318., 303., 312., 325.,
       328., 334., 336., 340., 322., 298., 295., 310., 300., 327., 338.,
       340., 331., 320., 299., 300., 304., 307., 308., 316., 313., 332.,
       326., 322., 329., 339., 321., 327., 313., 312., 334., 324., 322.,
       320., 316., 298., 300., 311., 309., 307., 304., 315., 325., 325.,
       327., 316., 318., 328., 332., 336., 321., 314., 314., 329., 327.,
       301., 296., 294., 312., 340., 320., 322., 340., 319., 315., 317.,
       314., 316., 318., 299., 298., 301., 303., 304., 306., 331., 332.,
       323., 322., 312., 314., 317., 326., 316., 329., 338., 331., 304.,
       305., 321., 301., 320., 311., 310., 299., 290., 296., 327., 335.,
       334., 310., 308., 301., 300., 323., 319., 326., 333., 339., 303.,
       309., 323., 333., 314., 312., 316., 326., 318., 329., 332., 331.,
       340., 325., 320., 315., 326., 339., 311., 33

Task 3 
Find the total number of  students who have a GRE score greater than 320

In [17]:
index = np.where(addmis_data[:,1]>320)
index

(array([  0,   1,   3,   5,   6,   9,  10,  11,  12,  21,  22,  23,  24,
         25,  26,  31,  32,  33,  34,  43,  44,  45,  46,  47,  48,  49,
         52,  53,  54,  64,  65,  66,  69,  70,  71,  72,  75,  76,  81,
         83,  84,  97,  98,  99, 100, 104, 106, 107, 108, 111, 119, 120,
        121, 126, 128, 129, 130, 133, 134, 138, 140, 141, 142, 143, 144,
        147, 148, 150, 151, 152, 153, 154, 164, 165, 171, 172, 173, 174,
        176, 185, 187, 188, 189, 190, 191, 192, 193, 202, 203, 210, 211,
        212, 213, 214, 215, 216, 217, 218, 222, 229, 234, 235, 236, 237,
        242, 243, 245, 248, 249, 253, 254, 257, 258, 259, 260, 263, 264,
        268, 275, 276, 283, 284, 285, 286, 287, 298, 302, 303, 305, 306,
        307, 311, 318, 319, 321, 325, 328, 330, 335, 337, 338, 339, 341,
        351, 356, 359, 360, 361, 362, 365, 371, 372, 373, 380, 382, 384,
        385, 392, 394, 395, 396, 397, 399], dtype=int64),)

In [18]:
addmis_data[index].size

1467

In [19]:
len(addmis_data[index])

163

Task 4 : What is the chance of admission of the students who have a TOEFL score greater than 110? Display the admission chance as a percentage number by multiplying each value in the output by 100.

In [20]:
addmis_data[:,2]


array([118., 107., 104., 110., 103., 115., 109., 101., 102., 108., 106.,
       111., 112., 109., 104., 105., 107., 106., 110., 102., 107., 114.,
       116., 119., 119., 120., 109.,  98.,  93.,  99.,  97., 103., 118.,
       114., 112., 110., 106., 105., 105., 108., 110., 105., 107., 117.,
       113., 110., 114., 119., 110., 111.,  98., 100., 116., 112., 110.,
       103., 102.,  99.,  99., 104., 100., 101., 105., 107., 111., 112.,
       114., 107., 109., 115., 118., 112., 111., 108., 106., 114., 112.,
        99.,  95.,  93., 105., 120., 110., 115., 115., 103., 106., 107.,
       108., 109., 106.,  97.,  98.,  97.,  99., 100., 100., 120., 119.,
       113., 107., 105., 106., 104., 112., 110., 111., 117., 116., 103.,
       108., 109., 107., 110., 105., 106., 102., 104.,  99., 104., 117.,
       119., 106., 108., 106., 100., 113., 112., 112., 118., 114., 105.,
       105., 112., 113., 109., 103., 100., 116., 109., 110., 118., 115.,
       120., 112., 113., 105., 114., 116., 106., 11

In [21]:
index = np.where(addmis_data[:,2]>110)
index

(array([  0,   5,  11,  12,  21,  22,  23,  24,  25,  32,  33,  34,  43,
         44,  46,  47,  49,  52,  53,  64,  65,  66,  69,  70,  71,  72,
         75,  76,  81,  83,  84,  97,  98,  99, 104, 106, 107, 108, 120,
        121, 126, 127, 128, 129, 130, 133, 134, 138, 141, 142, 143, 144,
        145, 147, 148, 150, 151, 152, 164, 171, 173, 174, 175, 176, 185,
        187, 188, 189, 190, 192, 193, 202, 203, 212, 213, 214, 215, 216,
        222, 228, 229, 234, 235, 236, 237, 242, 243, 249, 253, 254, 259,
        263, 268, 276, 283, 284, 285, 286, 287, 297, 298, 299, 307, 318,
        319, 325, 328, 330, 335, 337, 361, 362, 365, 372, 384, 385, 392,
        394, 397, 399], dtype=int64),)

In [22]:
addmis_data[:,8][index]*100

array([92., 90., 84., 78., 70., 94., 95., 97., 94., 91., 90., 94., 87.,
       91., 86., 89., 78., 78., 72., 52., 55., 61., 78., 94., 96., 93.,
       72., 74., 96., 92., 94., 86., 90., 79., 74., 87., 91., 93., 94.,
       94., 85., 78., 84., 92., 96., 79., 89., 80., 90., 92., 97., 80.,
       81., 83., 96., 93., 94., 86., 81., 89., 89., 87., 85., 90., 89.,
       93., 93., 88., 90., 86., 94., 97., 97., 95., 96., 94., 93., 91.,
       76., 71., 82., 91., 88., 85., 86., 70., 76., 77., 93., 85., 90.,
       70., 83., 89., 80., 94., 93., 92., 89., 86., 90., 71., 80., 79.,
       80., 81., 80., 80., 83., 94., 93., 91., 86., 95., 96., 96., 84.,
       89., 91., 95.])

Task 5 The university decides to offer a scholarship worth $1,000 to all those students who have a GRE score greater than 315, a TOEFL score greater than 115, and have some research experience.
Determine the total number of students eligible for this scholarship. Also, display the serial number of these students.

In [23]:
indx = (addmis_data[:,1]>315) & (addmis_data[:,2]>115) &(addmis_data[:,7]==1)
indx


array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,

In [24]:
addmis_data[indx]

array([[  1.  , 337.  , 118.  ,   4.  ,   4.5 ,   4.5 ,   9.65,   1.  ,
          0.92],
       [ 23.  , 328.  , 116.  ,   5.  ,   5.  ,   5.  ,   9.5 ,   1.  ,
          0.94],
       [ 24.  , 334.  , 119.  ,   5.  ,   5.  ,   4.5 ,   9.7 ,   1.  ,
          0.95],
       [ 25.  , 336.  , 119.  ,   5.  ,   4.  ,   3.5 ,   9.8 ,   1.  ,
          0.97],
       [ 26.  , 340.  , 120.  ,   5.  ,   4.5 ,   4.5 ,   9.6 ,   1.  ,
          0.94],
       [ 33.  , 338.  , 118.  ,   4.  ,   3.  ,   4.5 ,   9.4 ,   1.  ,
          0.91],
       [ 53.  , 334.  , 116.  ,   4.  ,   4.  ,   3.  ,   8.  ,   1.  ,
          0.78],
       [ 71.  , 332.  , 118.  ,   5.  ,   5.  ,   5.  ,   9.64,   1.  ,
          0.94],
       [ 82.  , 340.  , 120.  ,   4.  ,   5.  ,   5.  ,   9.5 ,   1.  ,
          0.96],
       [ 98.  , 331.  , 120.  ,   3.  ,   4.  ,   4.  ,   8.96,   1.  ,
          0.86],
       [ 99.  , 332.  , 119.  ,   4.  ,   5.  ,   4.5 ,   9.24,   1.  ,
          0.9 ],
       [108.  , 338. 

In [25]:
scholarship  =addmis_data[indx][:,0]
scholarship                                                     #serial number of the students eligible for scholarship


array([  1.,  23.,  24.,  25.,  26.,  33.,  53.,  71.,  82.,  98.,  99.,
       108., 109., 121., 122., 130., 139., 142., 144., 149., 152., 172.,
       177., 188., 194., 203., 204., 213., 214., 215., 216., 260., 286.,
       287., 326., 338., 362., 373., 386., 398., 400.])

In [26]:
scholarship.size       #total number of students eligible for scholarship


41